name: mobile_car_sim
description: "A new Flutter project."

publish_to: 'none' 

version: 1.0.0+1

environment:
  sdk: '>=3.2.2 <4.0.0'

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.2
  convert: ^3.1.1
  flutter_joystick: ^0.2.0
  flutter_riverpod: ^2.4.9
  network_info_plus: ^5.0.3
  wifi_info_plugin_plus: ^2.0.2
  hive: ^2.2.3
  path_provider: ^2.1.3
  json_annotation: ^4.9.0

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^2.0.0
  build_runner: ^2.3.3
  json_serializable: ^6.8.0

flutter:
  uses-material-design: true

  assets:
    # https://www.flaticon.com/free-icons/car-parts
    # Car parts icons created by smashingstocks - Flaticon
    - images/steering_wheel.png

    # https://www.flaticon.com/free-icons/brake
    # Brake icons created by Freepik - Flaticon
    - images/accelerator_pedal.png
    - images/brakes_pedal.png

    # https://www.flaticon.com/free-icons/automatic
    # Automatic icons created by amoghdesign - Flaticon
    - images/gear_base.png
    - images/gear_transmission.png
