name: release app

on:
  push:
    tags:
      - '[0-9]+.[0-9]+.[0-9]+'

  workflow_dispatch:

jobs:
  release-app:
    name: Release Client as ${{ matrix.build-type }} (${{ matrix.platform }})
    runs-on: ${{ matrix.os }}
    
    strategy:
      fail-fast: false
      matrix:
        include:
          - os: ubuntu-latest
            platform: android
            build-type: apk
          - os: windows-latest
            platform: windows
            build-type: windows
          - os: ubuntu-latest
            platform: linux
            build-type: debian
       
    steps:
      - uses: actions/checkout@v4
      - uses: subosito/flutter-action@v2
        with:
          flutter-version: '3.19.0'
          channel: 'stable'
      - uses: actions/setup-java@v4
        if: matrix.platform == 'android'
        with:
          # network info plus needs JDK 17
          distribution: 'temurin'
          java-version: '17'
      - name: View Directory
        run: pwd && ls -R
      - name: Build
        uses: oberhauser-dev/flutter-release-action@v0
        with:
          working-directory: '.'
          dry-run: false
          app-name: 'vegihle_car_sim'
          app-version: ${{ github.ref_name }}
          tag: ${{ github.ref }}
          build-type: ${{ matrix.build-type }}
          token: ${{ github.token }}
          publish-stage: internal
